server:
 port: 8380

spring:
 application:
    name: employee-service
 jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
 h2:
    console:
      enabled: true
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
